---
title: "RPPR 2021"
subtitle: "GWAS of Working Memory"
author: "Joey Trampush PhD"
date: "`r Sys.Date()`"
output: tint::tintPdf
bibliography: bib/master.bib
link-citations: yes
institute: University of Southern California
latex_engine: pdflatex
fancy: true
citation_package: biblatex
fig_caption: true
geometry: margin=0.5in
fontfamily: mathpazo
fontsize: 11pt
bibliography: bib/master.bib
biblio-style: apa
---

# Accomplishments

## B.1 What are the major goals of the project?

> List the major goals of the project as stated in the approved application or
> as approved by the agency. If the application lists milestones/target dates
> for important activities or phases of the project, identify these dates and
> show actual completion dates or the percentage of completion.

> Generally, the goals will not change from one reporting period to the next.
> However, if the awarding agency approved changes to the goals during the
> reporting period, list the revised goals and objectives. Also explain any
> significant changes in approach or methods from the agency approved
> application or plan.

> DHHS Specific Language "Goals" are equivalent to "specific aims." Significant
> changes in objectives and scope require prior approval of the agency (e.g.,
> NIH Grants Policy Statement, 8.1.2).

### List the major goals below

> NIH recommended length is up to 1 page. Limit is 8000 characters or
> approximately 3 pages

**Specific Aims**

### 1.a Have the major goals changed since the initial competing award or previous report? Yes No

## B.2 What was accomplished under these goals?

For this reporting period describe: 1) major activities; 2) specific objectives;
3) significant results, including major findings, developments, or conclusions
(both positive and negative); and 4) key outcomes or other achievements. Include
a discussion of stated goals not met. As the project progresses, the emphasis in
reporting in this section should shift from reporting activities to reporting
accomplishments.

DHHS Specific Language Goals are equivalent to specific aims. In the response,
emphasize the significance of the findings to the scientific field. Include the
approaches taken to ensure robust and unbiased results. For most NIH awards the
response should not exceed 2 pages.

## Upload accomplishments [**Add Attachment**]

## B.3 Competitive Revisions/Administrative Supplements

--------------------------------------------------------------------------------

For this reporting period, is there one or more Revision/Supplement associated
with this award for which reporting is required? Yes [x] No

If yes, identify the Revision(s)/Supplement(s) by grant number (e.g.,
3R01CA098765-01S1) or title and describe the specific aims and accomplishments
for each Revision/Supplement funded during this reporting period. Include any
supplements to promote diversity or re-entry, or other similar supplements to
support addition of an individual or a discrete project.

Revision/Supplement

or Revision/Supplement Title Total remaining allowed limit is 255 characters.
Describe the specific aims for this Revision/Supplement below (Limit is 700
characters or approximately 1/4 of a page.) Total remaining allowed limit is 700
characters. Describe the accomplishments for this Revision/Supplement below
(Limit is 700 characters or approximately 1/4 of a page.) Total remaining
allowed limit is 700 characters.

No items found. Revision/Supplement \# Revision/Supplement Title Specific Aims
Accomplishments Action Nothing found to display. ---

## B.4 What opportunities for training and professional development has the project provided?

--------------------------------------------------------------------------------

If the research is not intended to provide training and professional development
opportunities or there is nothing significant to report during this reporting
period, state "Nothing to Report."

Describe opportunities for training and professional development provided to
anyone who worked on the project or anyone who was involved in the activities
supported by the project. "Training" activities are those in which individuals
with advanced professional skills and experience assist others in attaining
greater proficiency. Training activities may include, for example, courses or
one-on-one work with a mentor. "Professional development" activities result in
increased knowledge or skill in one's area of expertise and may include
workshops, conferences, seminars, study groups, and individual study. Include
participation in conferences, workshops, and seminars not listed under major
activities.

DHHS Specific Language For all projects reporting graduate student and/or
postdoctoral participants in Section D. Participant, grantees are encouraged to
describe the use of Individual Development Plans (IDPs) for those participants.A
Do not include the actual IDP; instead include information to document that IDPs
are used to help manage the training for those individuals.

DHHS Specific Language For T, F, K, R25, R13, D43 and other awards or award
components designed to provide training and professional development
opportunities, a response is required. Do not reiterate what is reported under
Accomplishments. Limit the response to this reporting period.

Nothing to Report or [x] **Upload Description and Diversity Report, as
applicable**

#### High-Performance Computing

Computational research often requires resources that exceed those of a personal
laptop or desktop computer. High-performance computing aggregates the resources
from individual computers (known as nodes) into a cluster that works together to
perform advanced, specialized computing jobs. The Center for Advanced Research
Computing launched its new high-performance computing cluster, Discovery, in
August 2020. The new cluster marks a significant upgrade to the CARC's
cyberinfrastructure, and the first step in a major, user-focused overhaul of the
program. The Discovery cluster consists of 2 shared login nodes and a total of
around 11,000 CPU cores in around 500 compute nodes. The typical compute node
has dual 8 to 16 core processors and resides on a 56 gigabit FDR InfiniBand
backbone. Nearly 100 GB of storage space is provided for each user to store
important code and configuration files in their home directories, and the
BeeGFS/ZFS parallel project file system has a capacity of 8.4 PB of usable
space, with a default storage quota of 10 TB per Principal Investigator across
their projects. A rapidly growing fleet of state-of-the art multicore compute
nodes is available for data-intensive research jobs, backed by two 800 TB,
high-throughput scratch file systems. A low-latency, high-bandwidth InfiniBand
network fabric facilitates intense research workloads on large data sets.
Discovery includes an array of scientific software packages, both licensed and
open source, for engineering, molecular simulation, and computational chemistry.
Researchers can also install software packages or develop their own code within
their project's allotted storage. Discovery is free to use for all USC faculty,
research staff, and graduate students (with the approval of their faculty
advisor). For information on how to set up your account and start using the
cluster, see the Accounts page. If you anticipate working with legally
restricted or sensitive data (e.g., HIPAA-, FERPA-, or CUI-regulated data), see
the Secure Computing page. Researchers also have the option of participating in
the Condo Cluster Program (CCP). The CCP allows researchers to reserve computing
resources for dedicated use by their projects, giving them the flexibility of
having their own cluster without the responsibility of purchasing hardware or
performing maintenance. For more information on the CCP, see the Condo Cluster
Program page.

#### The Penn Letter N-Back Test

The Penn Letter N-Back Test measures working memory (WM), the ability to keep
and refresh goal-related information. Participants attend to a continual series
of letters that flash on the screen (one at a time) and press the spacebar
according to three different rules (called the 0-back, 1-back, and 2-back).
During the 0-back condition, the participant must simply respond to a currently
present target ("X"). During the 1-back condition, he/she must press the
spacebar when the letter on the screen is the same as the previous letter.
During the 2-back condition, he/she must press the spacebar when the letter on
the screen is the same as the letter before the previous letter (i.e. 2 letters
back). In all trials, the inter-stimulus interval (ISI) is 2.5 seconds, and the
stimuli (letters) themselves are presented for 0.5 seconds each. The participant
practices all three principles before testing.

--------------------------------------------------------------------------------

## B.5 How have the results been disseminated to communities of interest?

Describe how the results have been disseminated to communities of interest.
Include any outreach activities that have been undertaken to reach members of
communities who are not usually aware of these research activities, for the
purpose of enhancing public understanding and increasing interest in learning
and careers in science, technology, and the humanities.

DHHS Specific Language Reporting the routine dissemination of information (e.g.,
websites, press releases) is not required. For awards not designed to
disseminate information to the public or conduct similar outreach activities, a
response is not required and the grantee should select "Nothing to Report". A
detailed response is only required for awards or award components that are
designed to disseminate information to the public or conduct similar outreach
activities. Note that scientific publications and the sharing of research
sources will be reported under Products.

Nothing to Report

**or enter response below (NIH recommended length is up to 1 page.** Limit is
8000 characters or approximately 3 pages.)

Total remaining allowed limit is 8000 characters.

--------------------------------------------------------------------------------

## B.6 What do you plan to do during the next reporting period to accomplish the goals?

Describe briefly what you plan to do during the next reporting period to
accomplish the goals and objectives.

DHHS Specific Language Discuss efforts to ensure that the approach is
scientifically rigorous and results are robust and unbiased. Remember that
significant changes in objectives and scope require prior approval of the agency
(e.g., NIH Grants Policy Statement, 8.1.2.).

DHHS Specific Language Include any important modifications to the original
plans. Provide a scientific justification for any changes involving research
with human subjects or vertebrate animals. A detailed description of such
changes must be provided under Changes.

**Enter response below (NIH recommended length is up to 1 page. Limit is 8000
characters or approximately 3 pages.)** Total remaining allowed limit is 8000
characters.

> insert

> end

# Products

### publications, conference papers, and presentations

### website(s) or other Internet site(s)

### technologies or techniques

### inventions, patent applications, and/or licenses

### other products, such as data or databases, physical collections, audio or video products, software, models, educational aids or curricula, instruments or equipment, research material, interventions (e.g., clinical or educational), or new business creation.

# Participants and Other Collaborating Organizations

Amanda Law Jack Bowden

# Impact

Zero

# Changes/Problems (not required for Final or Interim RPPR)

### Changes in approach and reasons for change

### Actual or anticipated problems or delays and actions or plans to resolve them

### Changes that have a significant impact on expenditures

### Significant changes in use or care of human subjects, vertebrate animals, biohazards, and/or select agents

# Budgetary Information (not required for Final or Interim RPPR)

N/A

## Project Outcomes (only required on Final and Interim RPPR)

### Concise summary of the outcomes or findings of the award, written for the general public in clear and comprehensible language, without including any proprietary, confidential information or trade secrets

Note: project outcome information will be made public in NIH RePORTER Link to
External Site
