plink2 --vcf chr1.dose.vcf.gz 'dosage=HDS' --fam dns_b37_qc_eur_norel.fam --freq --make-pgen psam-cols=+fid --sort-vars 'natural' --out dns.chr1.binary.dosage &
plink2 --vcf chr2.dose.vcf.gz 'dosage=HDS' --fam dns_b37_qc_eur_norel.fam --freq --make-pgen psam-cols=+fid --sort-vars 'natural' --out dns.chr2.binary.dosage &
plink2 --vcf chr3.dose.vcf.gz 'dosage=HDS' --fam dns_b37_qc_eur_norel.fam --freq --make-pgen psam-cols=+fid --sort-vars 'natural' --out dns.chr3.binary.dosage &
plink2 --vcf chr4.dose.vcf.gz 'dosage=HDS' --fam dns_b37_qc_eur_norel.fam --freq --make-pgen psam-cols=+fid --sort-vars 'natural' --out dns.chr4.binary.dosage &
plink2 --vcf chr5.dose.vcf.gz 'dosage=HDS' --fam dns_b37_qc_eur_norel.fam --freq --make-pgen psam-cols=+fid --sort-vars 'natural' --out dns.chr5.binary.dosage &
plink2 --vcf chr6.dose.vcf.gz 'dosage=HDS' --fam dns_b37_qc_eur_norel.fam --freq --make-pgen psam-cols=+fid --sort-vars 'natural' --out dns.chr6.binary.dosage &
plink2 --vcf chr7.dose.vcf.gz 'dosage=HDS' --fam dns_b37_qc_eur_norel.fam --freq --make-pgen psam-cols=+fid --sort-vars 'natural' --out dns.chr7.binary.dosage &
plink2 --vcf chr8.dose.vcf.gz 'dosage=HDS' --fam dns_b37_qc_eur_norel.fam --freq --make-pgen psam-cols=+fid --sort-vars 'natural' --out dns.chr8.binary.dosage &
plink2 --vcf chr9.dose.vcf.gz 'dosage=HDS' --fam dns_b37_qc_eur_norel.fam --freq --make-pgen psam-cols=+fid --sort-vars 'natural' --out dns.chr9.binary.dosage &
plink2 --vcf chr10.dose.vcf.gz 'dosage=HDS' --fam dns_b37_qc_eur_norel.fam --freq --make-pgen psam-cols=+fid --sort-vars 'natural' --out dns.chr10.binary.dosage &
plink2 --vcf chr11.dose.vcf.gz 'dosage=HDS' --fam dns_b37_qc_eur_norel.fam --freq --make-pgen psam-cols=+fid --sort-vars 'natural' --out dns.chr11.binary.dosage &
plink2 --vcf chr12.dose.vcf.gz 'dosage=HDS' --fam dns_b37_qc_eur_norel.fam --freq --make-pgen psam-cols=+fid --sort-vars 'natural' --out dns.chr12.binary.dosage &
plink2 --vcf chr13.dose.vcf.gz 'dosage=HDS' --fam dns_b37_qc_eur_norel.fam --freq --make-pgen psam-cols=+fid --sort-vars 'natural' --out dns.chr13.binary.dosage &
plink2 --vcf chr14.dose.vcf.gz 'dosage=HDS' --fam dns_b37_qc_eur_norel.fam --freq --make-pgen psam-cols=+fid --sort-vars 'natural' --out dns.chr14.binary.dosage &
plink2 --vcf chr15.dose.vcf.gz 'dosage=HDS' --fam dns_b37_qc_eur_norel.fam --freq --make-pgen psam-cols=+fid --sort-vars 'natural' --out dns.chr15.binary.dosage &
plink2 --vcf chr16.dose.vcf.gz 'dosage=HDS' --fam dns_b37_qc_eur_norel.fam --freq --make-pgen psam-cols=+fid --sort-vars 'natural' --out dns.chr16.binary.dosage &
plink2 --vcf chr17.dose.vcf.gz 'dosage=HDS' --fam dns_b37_qc_eur_norel.fam --freq --make-pgen psam-cols=+fid --sort-vars 'natural' --out dns.chr17.binary.dosage &
plink2 --vcf chr18.dose.vcf.gz 'dosage=HDS' --fam dns_b37_qc_eur_norel.fam --freq --make-pgen psam-cols=+fid --sort-vars 'natural' --out dns.chr18.binary.dosage &
plink2 --vcf chr19.dose.vcf.gz 'dosage=HDS' --fam dns_b37_qc_eur_norel.fam --freq --make-pgen psam-cols=+fid --sort-vars 'natural' --out dns.chr19.binary.dosage &
plink2 --vcf chr20.dose.vcf.gz 'dosage=HDS' --fam dns_b37_qc_eur_norel.fam --freq --make-pgen psam-cols=+fid --sort-vars 'natural' --out dns.chr20.binary.dosage &
plink2 --vcf chr21.dose.vcf.gz 'dosage=HDS' --fam dns_b37_qc_eur_norel.fam --freq --make-pgen psam-cols=+fid --sort-vars 'natural' --out dns.chr21.binary.dosage &
plink2 --vcf chr22.dose.vcf.gz 'dosage=HDS' --fam dns_b37_qc_eur_norel.fam --freq --make-pgen psam-cols=+fid --sort-vars 'natural' --out dns.chr22.binary.dosage &
